const test=require('node:test');const assert=require('node:assert/strict');const {PGlite}=require('@electric-sql/pglite');const {wrap}=require('../config/postgres');const express=require('express');
test('employee APIs hide admins and enforce owner/manager and salary protections',async()=>{
 process.env.DATABASE_URL='postgres://fixture';const engine=new PGlite();
 const connection=wrap({async query(config,values){const r=await engine.query(typeof config==='string'?config:config.text,typeof config==='string'?values:config.values);return {...r,rowCount:r.affectedRows??r.rows.length};},release(){}});
 const db={...connection,getConnection:async()=>connection};const dbPath=require.resolve('../config/database');require.cache[dbPath]={id:dbPath,filename:dbPath,loaded:true,exports:db};
 await engine.exec(`CREATE TABLE users(user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_name varchar(30) UNIQUE,user_email varchar(100) UNIQUE,user_position varchar(50),access_level text,user_password_hash text,created_at timestamp DEFAULT CURRENT_TIMESTAMP);CREATE UNIQUE INDEX users_single_owner ON users(access_level) WHERE access_level='owner';CREATE TABLE position_salary_defaults(position_key text,position_name text,effective_month date,monthly_salary numeric,PRIMARY KEY(position_key,effective_month));INSERT INTO users(user_name,user_position,access_level) VALUES('Admin','Admin','admin'),('Owner','Owner','owner'),('Manager','Manager','manager'),('Employee','Cashier','employee');`);
 const app=express();app.use(express.json());app.use((req,res,next)=>{req.user={user_id:Number(req.get('Actor')),access_level:{1:'admin',2:'owner',3:'manager',4:'employee'}[req.get('Actor')]};next();});app.use('/api',require('../routes/employeeRout'));app.use('/api',require('../routes/payrollRout'));
 const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
 app.use('/api/auth',require('../routes/authRout'));
 const request=async(actor,url,method='GET',body)=>{const res=await fetch(`http://127.0.0.1:${server.address().port}/api${url}`,{method,headers:{Actor:String(actor),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json()};};
 try{
  const salaryOnly=await request(1,'/employees','POST',{name:'Normal employee',accessLevel:'payroll_only'});
  assert.equal(salaryOnly.status,201);
  const blocked=await fetch(`http://127.0.0.1:${server.address().port}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'Normal employee',password:'anything'})});
  assert.equal(blocked.status,403);
  assert.match((await blocked.json()).message,/salary management only/);
  await connection.execute('DELETE FROM users WHERE user_id = ?',[salaryOnly.data.user_id]);
  assert.equal((await request(1,'/employees')).data.length,4);
  assert.equal((await request(2,'/employees')).data.some(row=>row.access_level==='admin'),false);
  assert.deepEqual((await request(4,'/employees')).data,[]);
  assert.equal((await request(2,'/employees/2','PATCH',{name:'Changed'})).status,403);
  assert.equal((await request(3,'/employees/2','DELETE')).status,403);
  assert.equal((await request(1,'/employees/4','PATCH',{accessLevel:'owner'})).status,409);
  assert.equal((await request(1,'/employees/4','PATCH',{accessLevel:'manager'})).status,200);
  assert.equal((await request(2,'/employees/4','PATCH',{accessLevel:'manager'})).status,200);
  assert.equal((await request(1,'/employees/2/salary','PUT',{month:'2026-09',amount:100})).status,403);
  assert.equal((await request(1,'/employees/1/payroll-payment','PUT',{month:'2026-09',status:'paid',expectedAmount:100})).status,403);
  assert.equal((await request(4,'/employees/position-salaries','PUT',{position:'Cashier',month:'2026-09',amount:500})).status,403);
  assert.equal((await request(3,'/employees/position-salaries','PUT',{position:'Cashier',month:'2026-09',amount:500})).status,200);
  assert.equal(Number((await request(3,'/employees/position-salaries')).data[0].monthly_salary),500);
  assert.equal((await request(4,'/employees','POST',{name:'New employee',email:'new@example.invalid',password:'fixture-only',position:'Cashier',accessLevel:'employee'})).status,201);
 }finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await engine.close();}
});
