const { test } = require('node:test');
const assert = require('node:assert/strict');
const { PGlite } = require('@electric-sql/pglite');
const { wrap } = require('../config/postgres');
process.env.DATABASE_URL = 'postgresql://unused/test';
test('N/A shelf life saves null and produces undated batches', async () => {
  const { saveStockItem } = require('../services/stockItemService');
  const engine = new PGlite();
  await engine.exec('CREATE TABLE items(item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,item_name text,item_category text,uom text,safety_limit numeric,item_cost numeric,shelf_life integer,stock numeric,"stockStatus" text);');
  const client = { async query(config) { const result = await engine.query(config.text, config.values); return { ...result, rowCount: result.affectedRows ?? result.rows.length }; } };
  const db = wrap(client);
  await db.beginTransaction();
  try {
    const { item_id } = await saveStockItem(db, null, { stock_name: 'No expiry', stock_uom: 'pcs', stock_shelf_life: null });
    const [[item]] = await db.execute('SELECT shelf_life FROM items WHERE item_id = ?', [item_id]);
    assert.equal(item.shelf_life, null);
    const sql = require('../config/dialect');
    const [[result]] = await db.execute(`SELECT ${sql('DATE_ADD(CURRENT_DATE, INTERVAL (SELECT shelf_life FROM items WHERE item_id = ?) DAY)', '(CURRENT_DATE + (SELECT shelf_life FROM items WHERE item_id = ?))')} AS expiration`, [item_id]);
    assert.equal(result.expiration, null);
  } finally { await db.rollback(); await engine.close(); }
});

