const test=require('node:test');const assert=require('node:assert/strict');const {PGlite}=require('@electric-sql/pglite');const {wrap}=require('../config/postgres');
test('refund choices preserve orders, restore saved quantities only when requested, and cannot restock twice',async()=>{
 process.env.DATABASE_URL='postgres://fixture';const engine=new PGlite();
 const db=wrap({async query(config,values){const r=await engine.query(typeof config==='string'?config:config.text,typeof config==='string'?values:config.values);return {...r,rowCount:r.affectedRows??r.rows.length};},release(){}});
 const path=require.resolve('../config/database');require.cache[path]={id:path,filename:path,loaded:true,exports:{getConnection:async()=>db}};
 const refund=require('../services/refundService');
 try{
  await engine.exec(`CREATE TABLE items(item_id integer PRIMARY KEY,stock numeric,safety_limit numeric,shelf_life integer,"stockStatus" text);CREATE TABLE batches(batch_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,item_id integer,batch_stock numeric,"batch_exDate" date);CREATE TABLE orders_history(order_id text PRIMARY KEY,status text,details jsonb,refund_reason text,refunded_by integer,refunded_at timestamp);INSERT INTO items VALUES(1,10,5,3,'well');`);
  const details={items:[{product_id:2,qty:2}],recipe_snapshot:[{product_id:2,ingredients:[{item_id:1,qty:3}]}]};
  for(const id of ['return','keep','legacy'])await engine.query("INSERT INTO orders_history VALUES($1,'completed',$2,NULL,NULL,NULL)",[id,JSON.stringify(id==='legacy'?{items:details.items}:details)]);
  await refund('keep',{reason:'Prepared drink',returnToStock:false},7);assert.equal(Number((await db.query('SELECT stock FROM items'))[0][0].stock),10);
  await refund('return',{reason:'Cancelled before preparation',returnToStock:true},7);await refund('return',{reason:'Repeated request',returnToStock:true},7);
  assert.equal(Number((await db.query('SELECT stock FROM items'))[0][0].stock),16);assert.equal((await db.query('SELECT * FROM batches'))[0].length,1);
  await assert.rejects(refund('legacy',{reason:'Old sale',returnToStock:true},7),/no saved ingredient/);
  assert.equal((await db.query("SELECT status FROM orders_history WHERE order_id = 'legacy'"))[0][0].status,'completed');
  await refund('legacy',{reason:'Old sale',returnToStock:false},7);assert.equal((await db.query('SELECT * FROM orders_history'))[0].length,3);
 }finally{await engine.close();}
});
