import {useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Settings,ArrowRightLeft,X} from 'lucide-react';
import {useCurrency} from '../global.jsx';
import './CurrencyControls.css';
export default function CurrencyControls(){
 const {currency,toggleCurrency,rate,changeRate}=useCurrency();
 const dialog=useRef(null);const [value,setValue]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 function open(){setValue(String(rate));setError('');dialog.current.showModal();}
 async function save(event){event.preventDefault();if(busy)return;const next=Number(value);if(!Number.isFinite(next)||next<=0){setError('Enter an exchange rate greater than zero.');return;}setBusy(true);setError('');try{await changeRate(next);dialog.current.close();}catch(issue){setError(issue.response?.data?.error||issue.message||'Could not save the shared rate.');}finally{setBusy(false);}}
 return <><div className="currency-controls"><button type="button" className="currency-switch" onClick={toggleCurrency} aria-label={'Change currency from '+currency} title="Switch USD / L.L.">{currency==='USD'?'USD':'L.L.'}</button><button type="button" className="currency-rate-icon" aria-label="Exchange rate settings" title="Exchange rate settings" onClick={open}><Settings size={18}/></button></div>
 {createPortal(<dialog ref={dialog} className="currency-rate-dialog" aria-labelledby="currency-rate-title" onCancel={event=>{if(busy)event.preventDefault();}}><form onSubmit={save}><header><div className="currency-rate-heading"><span><ArrowRightLeft size={21}/></span><h2 id="currency-rate-title">Exchange rate</h2></div><button type="button" disabled={busy} aria-label="Close exchange rate settings" onClick={()=>dialog.current.close()}><X size={20}/></button></header><p>Set how many Lebanese pounds equal one US dollar. This rate is shared by all laptops. An internet connection is required to save.</p><label htmlFor="currency-rate-value">1 USD equals</label><div className="currency-rate-input"><input id="currency-rate-value" type="number" inputMode="decimal" min="0.000001" step="any" required disabled={busy} value={value} onChange={e=>setValue(e.target.value)} autoFocus/><span>L.L.</span></div><p className="currency-rate-current">Current rate: 1 USD = {Number(rate).toLocaleString()} L.L.</p>{error&&<p role="alert">{error}</p>}<footer><button type="button" disabled={busy} onClick={()=>dialog.current.close()}>Cancel</button><button type="submit" className="currency-rate-save" disabled={busy}>{busy?'Saving...':'Save rate'}</button></footer></form></dialog>,document.body)}</>;
}
