CREATE TABLE IF NOT EXISTS business_expenses (
  expense_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(30) NOT NULL,
  description VARCHAR(200) NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  expense_date DATE NOT NULL,
  recorded_by INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_business_expense_date ON business_expenses(expense_date);
ALTER TABLE business_expenses ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON business_expenses FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON business_expenses FROM authenticated; END IF;
END $$;

CREATE TABLE IF NOT EXISTS expense_recurrences (
  expense_id BIGINT PRIMARY KEY REFERENCES business_expenses(expense_id) ON DELETE CASCADE,
  frequency VARCHAR(10) NOT NULL,
  repeat_until DATE NULL,
  stopped_before DATE NULL
);
ALTER TABLE expense_recurrences ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON expense_recurrences FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON expense_recurrences FROM authenticated; END IF;
END $$;
