-- PostgreSQL/Supabase baseline. Run once against an empty project's public schema.
-- Existing MySQL IDs, password hashes, dates and JSON are preserved by migrate-supabase.js.
CREATE TABLE users (
 user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_name varchar(30) NOT NULL UNIQUE, user_email varchar(100) NOT NULL UNIQUE,
 user_password_hash varchar(100) NOT NULL, user_position varchar(50) NOT NULL,
 access_level text NOT NULL DEFAULT 'employee' CHECK (access_level IN ('admin','employee')),
 telegram_id varchar(30) UNIQUE, created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE floors (
 floor_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 floor_name varchar(25) UNIQUE, display_order integer UNIQUE
);
CREATE TABLE tablez (
 t_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 floor_id integer REFERENCES floors ON DELETE CASCADE, t_name varchar(50) UNIQUE,
 t_type varchar(20), t_status varchar(20), t_seats integer
);
CREATE TABLE item_categories (
 i_category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 i_category_name varchar(30) NOT NULL UNIQUE
);
CREATE TABLE items (
 item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 item_name varchar(30) NOT NULL UNIQUE, item_category varchar(30), stock decimal(10,2) DEFAULT 0,
 uom varchar(30) NOT NULL, safety_limit decimal(10,2) DEFAULT 0, item_cost decimal(10,2) DEFAULT 0,
 "exDate" date, "stockStatus" varchar(30), shelf_life integer DEFAULT 0
);
CREATE TABLE suppliers (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 item_id integer UNIQUE REFERENCES items ON DELETE CASCADE,
 supplier_name varchar(30) NOT NULL, supplier_contact varchar(30)
);
CREATE TABLE batches (
 batch_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 item_id integer REFERENCES items ON DELETE CASCADE, batch_stock decimal(10,2) DEFAULT 0, "batch_exDate" date
);
CREATE TABLE product_categories (
 p_category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 p_category_name varchar(30) NOT NULL UNIQUE
);
CREATE TABLE products (
 product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_name varchar(30) UNIQUE, product_category varchar(30), product_price decimal(10,2) DEFAULT 0
);
CREATE TABLE product_items (
 recipe_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id integer REFERENCES products ON DELETE CASCADE,
 item_id integer REFERENCES items ON DELETE CASCADE, qty decimal(10,2) DEFAULT 1
);
CREATE TABLE monthly_order_sequences (
 order_month varchar(6) PRIMARY KEY, current_sequence integer NOT NULL DEFAULT 0
);
CREATE TABLE orders_history (
 internal_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id varchar(20) UNIQUE, customer_name varchar(30) DEFAULT 'Guest',
 total_amount decimal(10,2) NOT NULL, details jsonb NOT NULL, order_date timestamp DEFAULT CURRENT_TIMESTAMP,
 status text NOT NULL DEFAULT 'completed' CHECK (status IN ('completed','refunded')),
 refund_reason varchar(500), refund_evidence text,
 refunded_by integer REFERENCES users ON DELETE SET NULL, refunded_at timestamp
);
CREATE TABLE recurring_shifts (
 recurrence_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer NOT NULL REFERENCES users ON DELETE CASCADE,
 month_days jsonb, weekdays jsonb, starts_on date NOT NULL, stopped_from date,
 start_time time NOT NULL, end_time time NOT NULL, notes varchar(255),
 created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK (end_time > start_time)
);
CREATE TABLE shifts (
 shift_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer NOT NULL REFERENCES users ON DELETE CASCADE, shift_date date NOT NULL,
 start_time time NOT NULL, end_time time NOT NULL, notes varchar(255),
 created_at timestamp DEFAULT CURRENT_TIMESTAMP,
 recurrence_id integer REFERENCES recurring_shifts ON DELETE SET NULL, cancelled_at timestamp,
 UNIQUE (recurrence_id, shift_date), CHECK (end_time > start_time)
);
CREATE TABLE workflow_requests (
 request_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer NOT NULL REFERENCES users ON DELETE CASCADE,
 request_type text NOT NULL CHECK (request_type IN ('shift_checkin','stock_receipt','stock_usage','refund')),
 payload jsonb NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
 reviewed_by integer REFERENCES users ON DELETE SET NULL, review_note varchar(500),
 created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, reviewed_at timestamp, bot_notified_at timestamp
);
CREATE TABLE shift_checkins (
 checkin_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer NOT NULL REFERENCES users ON DELETE CASCADE,
 shift_id integer REFERENCES shifts ON DELETE SET NULL, checked_in_at timestamp NOT NULL,
 approved_by integer NOT NULL REFERENCES users
);
CREATE TABLE employee_salary_rates (
 user_id integer NOT NULL REFERENCES users ON DELETE CASCADE, effective_month date NOT NULL,
 monthly_salary decimal(12,2) NOT NULL CHECK (monthly_salary >= 0),
 updated_by integer REFERENCES users ON DELETE SET NULL,
 updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (user_id, effective_month)
);
CREATE TABLE salary_deductions (
 deduction_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer NOT NULL REFERENCES users ON DELETE CASCADE,
 request_id integer NOT NULL UNIQUE REFERENCES workflow_requests ON DELETE CASCADE,
 order_id varchar(20) NOT NULL, amount decimal(12,2) NOT NULL CHECK (amount >= 0), deducted_at timestamp NOT NULL,
 UNIQUE (user_id, order_id)
);
CREATE TABLE employee_payroll_payments (
 user_id integer NOT NULL REFERENCES users ON DELETE CASCADE, salary_month date NOT NULL,
 status text NOT NULL CHECK (status IN ('paid','unpaid')), amount_paid decimal(12,2) NOT NULL DEFAULT 0,
 paid_at timestamp, paid_by integer REFERENCES users ON DELETE SET NULL, PRIMARY KEY (user_id, salary_month)
);
CREATE TABLE payroll_payment_events (
 event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer NOT NULL REFERENCES users ON DELETE CASCADE, salary_month date NOT NULL,
 status text NOT NULL CHECK (status IN ('paid','unpaid')), amount decimal(12,2) NOT NULL,
 recorded_by integer REFERENCES users ON DELETE SET NULL, recorded_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- Preserve case-insensitive account uniqueness when moving from MySQL's collation.
CREATE UNIQUE INDEX users_name_case_insensitive ON users (LOWER(user_name));
CREATE UNIQUE INDEX users_email_case_insensitive ON users (LOWER(user_email));
CREATE INDEX ON tablez (floor_id);
CREATE INDEX ON batches (item_id);
CREATE INDEX ON product_items (product_id);
CREATE INDEX ON product_items (item_id);
CREATE INDEX ON shifts (user_id, shift_date);
CREATE INDEX ON recurring_shifts (user_id, starts_on);
CREATE INDEX ON workflow_requests (status, created_at);
CREATE INDEX ON workflow_requests (user_id);
CREATE INDEX ON shift_checkins (user_id, checked_in_at);
CREATE INDEX ON shift_checkins (shift_id);
CREATE INDEX ON salary_deductions (user_id, deducted_at);
CREATE INDEX ON payroll_payment_events (user_id, salary_month);

-- Preserve the local database's expiration triggers (including refunds and bot receipts).
CREATE FUNCTION refresh_batch_expiration() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP <> 'INSERT' THEN
  UPDATE items SET "exDate" = (SELECT MIN("batch_exDate") FROM batches
   WHERE item_id = OLD.item_id AND batch_stock > 0) WHERE item_id = OLD.item_id;
 END IF;
 IF TG_OP <> 'DELETE' THEN
  UPDATE items SET "exDate" = (SELECT MIN("batch_exDate") FROM batches
   WHERE item_id = NEW.item_id AND batch_stock > 0) WHERE item_id = NEW.item_id;
 END IF;
 RETURN NULL;
END;
$$;
CREATE TRIGGER batch_expiration AFTER INSERT OR UPDATE OR DELETE ON batches
 FOR EACH ROW EXECUTE FUNCTION refresh_batch_expiration();

CREATE FUNCTION refresh_salary_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
$$;
CREATE TRIGGER salary_updated_at BEFORE UPDATE ON employee_salary_rates
 FOR EACH ROW EXECUTE FUNCTION refresh_salary_updated_at();

-- Authentication stays in Express. No direct access from Supabase's browser Data API.
DO $$
DECLARE table_name text;
BEGIN
 FOREACH table_name IN ARRAY ARRAY['users','floors','tablez','item_categories','items','suppliers','batches',
 'product_categories','products','product_items','monthly_order_sequences','orders_history','recurring_shifts',
 'shifts','workflow_requests','shift_checkins','employee_salary_rates','salary_deductions',
 'employee_payroll_payments','payroll_payment_events'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
   EXECUTE format('REVOKE ALL ON public.%I FROM anon', table_name);
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
   EXECUTE format('REVOKE ALL ON public.%I FROM authenticated', table_name);
  END IF;
 END LOOP;
END;
$$;

-- Business expenses
CREATE TABLE IF NOT EXISTS business_expenses (
  expense_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(30) NOT NULL,
  description VARCHAR(200) NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  expense_date DATE NOT NULL,
  recorded_by INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_business_expense_date ON business_expenses(expense_date);
ALTER TABLE business_expenses ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON business_expenses FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON business_expenses FROM authenticated; END IF;
END $$;

CREATE TABLE IF NOT EXISTS expense_recurrences (
  expense_id BIGINT PRIMARY KEY REFERENCES business_expenses(expense_id) ON DELETE CASCADE,
  frequency VARCHAR(10) NOT NULL,
  repeat_until DATE NULL,
  stopped_before DATE NULL
);
ALTER TABLE expense_recurrences ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON expense_recurrences FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON expense_recurrences FROM authenticated; END IF;
END $$;
